blank_issues_enabled: false
contact_links:
  - name: Features, Bug Reports, Questions
    url: https://github.com/denisemignoli/ai-contributions-gate/discussions/new/choose
    about: Use Discussions primeiro. Nosso ponto de partida preferido para dúvidas, sugestões e reports de bugs.
