name: Features, Bugs, Questions
description: Use Discussions primeiro
title: "[REDIRECT] "
body:
  - type: markdown
    attributes:
      value: |
        🚫 Não abra issue diretamente.

        👉 Vá para Discussions:
        https://github.com/denisemignoli/ai-contributions-gate/discussions/new/choose

  - type: input
    attributes:
      label: Confirmação
      description: Digite qualquer coisa para continuar
    validations:
      required: true